language: node_js

node_js:
  - '12'
  - '10'

cache: yarn

before_install:
  - npx replace-pkg-dep

install:
  - yarn install

script:
  - jest --coverage --coverageReporters text lcovonly

after_success:
  - cat ./coverage/lcov.info | coveralls
